server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://182.92.205.89:3306/wx_question?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: boot.wx.entity
